
CREATE DATABASE IF NOT EXISTS cadeau;

USE cadeau;

CREATE TABLE IF NOT EXISTS `user` (
  `userID` INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  `userName` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

CREATE TABLE IF NOT EXISTS `idea` (
  `ideaID` INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  `ideaName` VARCHAR(255) NOT NULL,
  `user_id` INT NOT NULL,
  CONSTRAINT FK_UserIdea FOREIGN KEY (user_id)
  REFERENCES user (userID)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;
